# Definir des services app et db
services:
    app:
        build: . # Créer une image à partir du Dockerfile courant
        image: laravelapp
        entrypoint: ["/bin/sh", "/project/entrypoint.sh"]
        restart: unless-stopped
        ports:
            - "7000:8000"
        volumes:
            - ./app:/project
        depends_on:
            - db
    db:
        image: postgres:15
        volumes:
            - dbdata:/var/lib/postgresql/data
        #env_file:
            #- .env
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
    dbdata:
    
    
